//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasovHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution_rooms
    {
        public int id_DR { get; set; }
        public Nullable<int> Client { get; set; }
        public Nullable<int> Room { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
