//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasovHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms_service
    {
        public int id_RS { get; set; }
        public Nullable<int> Staff { get; set; }
        public Nullable<int> Room { get; set; }
    
        public virtual Rooms Rooms { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
